project_id = "loxpoehsddfearnzcdla"

[functions.sync-all-users-to-auth]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
[auth.email]
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54327

[functions.auth-webhook]
verify_jwt = false

[functions.webhook-lead]
verify_jwt = false

[functions.webhook-lead-recuperar]
verify_jwt = false

[functions.webhook-lead-vivaz]
verify_jwt = false

[functions.webhook-lead-vivaz-zona-sul]
verify_jwt = false

[functions.webhook-lead-vivaz-zona-leste]
verify_jwt = false

[functions.webhook-lead-araujo-broker]
verify_jwt = false

[functions.webhook-lead-mays-imob]
verify_jwt = false

[functions.webhook-lead-janaina-vidalete]
verify_jwt = false

[functions.create-company]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.webhook-lead-click-imoveis]
verify_jwt = false

[functions.webhook-lead-click-imoveis-nao-qualificado]
verify_jwt = false

[functions.webhook-lead-rkmf-imoveis]
verify_jwt = false

[functions.webhook-lead-rkmf-imoveis-nao-qualificado]
verify_jwt = false